.PHONY: test verify build

test:
	go test -timeout 180s ./...

verify:
	test -z "$$(gofmt -l .)"
	go vet ./...
	go test -race -timeout 240s ./...
	go run honnef.co/go/tools/cmd/staticcheck@v0.7.0 ./...
	go run golang.org/x/vuln/cmd/govulncheck@v1.6.0 ./...

build:
	go build -trimpath -o releaseguard ./cmd/releaseguard
